//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Butler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutominerLocation> AutominerLocations { get; set; }
        public virtual DbSet<DroniteField> DroniteFields { get; set; }
        public virtual DbSet<POISpot> POISpots { get; set; }
        public virtual DbSet<ShipsToKill> ShipsToKills { get; set; }
        public virtual DbSet<TraderLocation> TraderLocations { get; set; }
    }
}
