//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Butler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipsToKill
    {
        public decimal ID { get; set; }
        public string ShipName { get; set; }
        public string SolarSystem { get; set; }
        public string Sector { get; set; }
    }
}
